version: '2'

services:
    saveimage:
        image: vladwing/save-image
        depends_on:
         - selenium
        networks:
         - selenium
        volumes:
         - save-image-storage:/srv/save-image/output
        command:
         - "--driver-ip"
         - "selenium:4444"
         - "--width"
         - "800"
         - "--height"
         - "600"
         - "-o"
         - "/srv/save-image/output/urad.jpg"
         - "http://agile.ro/urad/"
    http:
        image: nginx:1.11-alpine
        volumes:
         - save-image-storage:/usr/share/nginx/html:ro
        networks:
         - external
        ports:
         - "8050:80"
    selenium:
        image: selenium/standalone-chrome
        volumes:
         - /dev/shm:/dev/shm
        networks:
         - selenium
networks:
    selenium:
    external:
volumes:
    save-image-storage:
